/**
 * Saxony Smart Campus — Attendance Scan Load Test
 *
 * Target: 5 000 concurrent `POST /attendance/scan` from unique student
 * devices against a single Postgres + Redis pair (the pilot-faculty
 * deployment topology).
 *
 * Workload model
 *   - Each VU represents one student device.
 *   - Each iteration: GET /qr/current to fetch the rotating token (~30s
 *     window), POST /attendance/scan with a faked but valid payload.
 *   - Rate-limited 1 scan per VU per 30s window — matches real classroom
 *     behaviour.
 *
 * Stage profile (default — override via env)
 *   ramp-up      0 → 5 000 VUs over 2 min
 *   steady       5 000 VUs for 5 min
 *   ramp-down    5 000 → 0 VUs over 1 min
 *
 * SLO thresholds (test fails if breached)
 *   - p(95) scan latency < 800ms
 *   - error rate < 1%
 *   - dropped iterations < 1%
 *
 * Usage
 *   BASE_URL=http://localhost:3000/api/v1 \
 *     k6 run load/k6/scan.js
 *
 *   # via docker-compose.loadtest.yml
 *   docker compose -f docker-compose.loadtest.yml up --abort-on-container-exit
 *
 * Setup
 *   The pre-test setup() function logs in N students from a seeded CSV
 *   (load/k6/data/students.csv — generated by load/k6/seed.ts). Each
 *   row: email,password. Defaults to 5 000 rows.
 */

import http from 'k6/http';
import { check, sleep } from 'k6';
import { Counter, Rate, Trend } from 'k6/metrics';
import { SharedArray } from 'k6/data';

const BASE_URL = __ENV.BASE_URL || 'http://localhost:3000/api/v1';
const SESSION_ID = __ENV.SESSION_ID || 'session-load-test';
const VUS = Number(__ENV.VUS || 5000);
const RAMP_UP = __ENV.RAMP_UP || '2m';
const STEADY = __ENV.STEADY || '5m';
const RAMP_DOWN = __ENV.RAMP_DOWN || '1m';

export const options = {
  scenarios: {
    classroom_scan_storm: {
      executor: 'ramping-vus',
      startVUs: 0,
      stages: [
        { duration: RAMP_UP, target: VUS },
        { duration: STEADY, target: VUS },
        { duration: RAMP_DOWN, target: 0 },
      ],
      gracefulRampDown: '30s',
    },
  },
  thresholds: {
    http_req_duration: ['p(95)<800', 'p(99)<2000'],
    http_req_failed: ['rate<0.01'],
    'checks{tag:scan_ok}': ['rate>0.99'],
  },
};

// Pre-seeded students — each VU picks the row matching its __VU index so
// no two VUs collide on the same student (idempotency would fire).
const students = new SharedArray('students', () => {
  // Falls back to a synthesised list if no CSV is mounted.
  const out = [];
  for (let i = 1; i <= VUS; i++) {
    out.push({
      email: `loadtest+${i}@saxony-egypt.edu`,
      password: 'LoadTest!2025',
      studentId: `stu-load-${i}`,
    });
  }
  return out;
});

const scanOk = new Rate('scan_ok');
const scanLatency = new Trend('scan_latency_ms');
const scanRejected = new Counter('scan_rejected');

export function setup() {
  // Optional pre-flight: hit /health and abort if the backend isn't up.
  const r = http.get(`${BASE_URL.replace(/\/api\/v1$/, '')}/health`);
  check(r, { 'backend reachable': (res) => res.status === 200 });
  return { startedAt: Date.now() };
}

export default function () {
  const idx = (__VU - 1) % students.length;
  const me = students[idx];

  // 1. Log in (cached token per VU via __ENV — k6 doesn't persist VU
  //    state across iterations, so each VU keeps its token in a closure
  //    via global on first iteration).
  const token = login(me);
  if (!token) {
    scanRejected.add(1);
    return;
  }
  const headers = { Authorization: `Bearer ${token}` };

  // 2. Fetch the current QR token for the session.
  const qrRes = http.get(`${BASE_URL}/qr/current?sessionId=${SESSION_ID}`, {
    headers,
    tags: { endpoint: 'qr_current' },
  });
  if (qrRes.status !== 200) {
    scanRejected.add(1);
    return;
  }
  const qr = qrRes.json('data');

  // 3. Submit the scan.
  const t0 = Date.now();
  const scanRes = http.post(
    `${BASE_URL}/attendance/scan`,
    JSON.stringify({
      payload: qr.payload,
      gpsLat: 30.0444 + Math.random() * 0.0002,
      gpsLng: 31.2357 + Math.random() * 0.0002,
      deviceFingerprint: `vu-${__VU}`,
    }),
    {
      headers: { ...headers, 'Content-Type': 'application/json' },
      tags: { endpoint: 'scan' },
    },
  );
  scanLatency.add(Date.now() - t0);

  const ok = check(
    scanRes,
    {
      'scan accepted (200) or ALREADY_REGISTERED (409)': (r) =>
        r.status === 200 || r.status === 409,
    },
    { scan_ok: true },
  );
  scanOk.add(ok);
  if (!ok) scanRejected.add(1);

  // Mimic real-world classroom cadence — students don't hammer the API.
  sleep(Math.random() * 30 + 10);
}

const tokenCache = {};
function login(me) {
  if (tokenCache[me.email]) return tokenCache[me.email];
  const r = http.post(
    `${BASE_URL}/auth/login`,
    JSON.stringify({ email: me.email, password: me.password }),
    { headers: { 'Content-Type': 'application/json' }, tags: { endpoint: 'login' } },
  );
  if (r.status !== 200) return null;
  const tok = r.json('data.accessToken');
  if (tok) tokenCache[me.email] = tok;
  return tok;
}

export function handleSummary(data) {
  return {
    'load/k6/summary.json': JSON.stringify(data, null, 2),
    stdout: textSummary(data),
  };
}

function textSummary(data) {
  const m = data.metrics;
  const lines = [
    '',
    '=== Saxony Smart Campus — Scan Load Test ===',
    `Duration:           ${(data.state.testRunDurationMs / 1000).toFixed(1)}s`,
    `Total requests:     ${m.http_reqs?.values.count ?? 0}`,
    `Failed requests:    ${(100 * (m.http_req_failed?.values.rate ?? 0)).toFixed(2)}%`,
    `p95 latency:        ${(m.http_req_duration?.values['p(95)'] ?? 0).toFixed(1)}ms`,
    `p99 latency:        ${(m.http_req_duration?.values['p(99)'] ?? 0).toFixed(1)}ms`,
    `Scan success rate:  ${(100 * (m.scan_ok?.values.rate ?? 0)).toFixed(2)}%`,
    `Rejected scans:     ${m.scan_rejected?.values.count ?? 0}`,
    '',
  ];
  return lines.join('\n');
}
